services:
  keyfile-generator:
    image: mongo
    container_name: keyfile_generator_container
    restart: 'no'
    command: >
      bash -c "
        set -e;
        mkdir -p /data/keyfile;
        if [ ! -f /data/keyfile/mongo-keyfile ]; then
          openssl rand -base64 756 > /data/keyfile/mongo-keyfile;
          echo 'Keyfile generated successfully.';
        else
          echo 'Keyfile already exists.';
        fi;
        chmod 400 /data/keyfile/mongo-keyfile;
        chown 999:999 /data/keyfile/mongo-keyfile;
      "
    volumes:
      - keyfile_volume:/data/keyfile

  mongo_test_one:
    image: mongo
    container_name: mongo_test_one_container
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all', '--keyFile', '/data/keyfile/mongo-keyfile']
    depends_on:
      keyfile-generator:
        condition: service_completed_successfully
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 4567890321
    ports:
      - '27017:27017'
    volumes:
      - mongo_test_one_data:/data/db
      - keyfile_volume:/data/keyfile:ro

  mongo_test_two:
    image: mongo
    container_name: mongo_test_two_container
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all', '--keyFile', '/data/keyfile/mongo-keyfile']
    depends_on:
      keyfile-generator:
        condition: service_completed_successfully
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 4567890321
    ports:
      - '27018:27017'
    volumes:
      - mongo_test_two_data:/data/db
      - keyfile_volume:/data/keyfile:ro

  mongo_init_replica:
    image: mongo
    container_name: mongo_init_replica_container
    depends_on:
      mongo_test_one:
        condition: service_started
      mongo_test_two:
        condition: service_started
    command: >
      bash -c "
        set -e;
        echo 'Waiting for MongoDB nodes to be ready...';
        until mongosh 'mongodb://admin:4567890321@mongo_test_one:27017/admin' --eval 'db.adminCommand(\"ping\")' >/dev/null 2>&1; do sleep 2; done;
        until mongosh 'mongodb://admin:4567890321@mongo_test_two:27017/admin' --eval 'db.adminCommand(\"ping\")' >/dev/null 2>&1; do sleep 2; done;
        echo 'Both nodes are up, ensuring replica set is initialized...';
        mongosh 'mongodb://admin:4567890321@mongo_test_one:27017/admin' --eval '
          const config = {
            _id: \"rs0\",
            members: [
              { _id: 0, host: \"mongo_test_one:27017\" },
              { _id: 1, host: \"mongo_test_two:27017\" }
            ]
          };
          let initialized = false;
          try {
            const status = rs.status();
            initialized = status.ok === 1;
          } catch (error) {
            if (error.codeName !== \"NotYetInitialized\") {
              throw error;
            }
          }
          if (!initialized) {
            rs.initiate(config);
          }
          let retries = 30;
          while (retries-- > 0) {
            try {
              const state = rs.status();
              if (state.ok === 1 && state.members && state.members.some(member => member.stateStr === \"PRIMARY\")) {
                quit(0);
              }
            } catch (statusError) {
              if (statusError.codeName !== \"NotYetInitialized\") {
                throw statusError;
              }
            }
            sleep(1000);
          }
          throw new Error(\"Replica set did not reach PRIMARY state in time.\");
        ';
        echo 'Replica set ready.';
      "

  node_server_test:
    build:
      context: .
      dockerfile: Dockerfile.Test
    container_name: node_server_test_container
    env_file:
      - .env.test
    ports:
      - '8000:8000'
    depends_on:
      mongo_init_replica:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'node -e "fetch(''http://127.0.0.1:8000/'').then(res => (res.ok ? process.exit(0) : process.exit(1))).catch(() => process.exit(1));"'
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  keyfile_volume:
  mongo_test_one_data:
  mongo_test_two_data:
